### ISSUE TITLE
Snapping breaks on new jQuery

### ISSUE THREAD

**Issue by colemickens** [blackdynamo/jquerymobile-carousel#6]
We were working with jquery 1.4.8 and then upgraded to a newer version of jquery. We later realized that the snapping feature of jquery mobile carousel stopped working. It turns out it was a result of bumping jquery's version. Has anyone else experienced this or know of a way to use mobile carousel with the newest version of jquery.

**Comment by ngraef** [comment]
The issue is that jquery (starting with 1.6) no longer reports event.pageX and event.pageY. These need to be changed to event.originalEvent.pageX and event.originalEvent.pageY.

**Comment by scruffian** [comment]
Thanks. If anyone wants to fix this, just change data.pageX and data.pageY to data.originalEvent.pageX and data.originalEvent.pageY.
